# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#

#MXN clabe accounts from https://es.wikipedia.org/wiki/CLABE

ClabeAccount.create(abm_code: '002', short_name:'BANAMEX', corporate_name:'Banco Nacional de México, S.A., Institución de Banca Múltiple, Grupo Financiero Banamex')
ClabeAccount.create(abm_code: '006', short_name:'BANCOMEXT', corporate_name:'Banco Nacional de Comercio Exterior, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo')
ClabeAccount.create(abm_code: '009', short_name:'BANOBRAS', corporate_name:'Banco Nacional de Obras y Servicios Públicos, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo')
ClabeAccount.create(abm_code: '012', short_name:'BBVA BANCOMER', corporate_name:'BBVA Bancomer, S.A., Institución de Banca Múltiple, Grupo Financiero BBVA Bancomer')
ClabeAccount.create(abm_code: '014', short_name:'SANTANDER', corporate_name:'Banco Santander (México), S.A., Institución de Banca Múltiple, Grupo Financiero Santander')
ClabeAccount.create(abm_code: '019', short_name:'BANJERCITO', corporate_name:'Banco Nacional del Ejército, Fuerza Aérea y Armada, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo')
ClabeAccount.create(abm_code: '021', short_name:'HSBC', corporate_name:'HSBC México, S.A., Institución De Banca Múltiple, Grupo Financiero HSBC')
ClabeAccount.create(abm_code: '030', short_name:'BAJIO', corporate_name:'Banco del Bajío, S.A., Institución de Banca Múltiple')
ClabeAccount.create(abm_code: '032', short_name:'IXE', corporate_name:'IXE Banco, S.A., Institución de Banca Múltiple, IXE Grupo Financiero')
ClabeAccount.create(abm_code: '036', short_name:'INBURSA', corporate_name:'Banco Inbursa, S.A., Institución de Banca Múltiple, Grupo Financiero Inbursa')
ClabeAccount.create(abm_code: '037', short_name:'INTERACCIONES', corporate_name:'Banco Interacciones, S.A., Institución de Banca Múltiple')
ClabeAccount.create(abm_code: '042', short_name:'MIFEL', corporate_name:'Banca Mifel, S.A., Institución de Banca Múltiple, Grupo Financiero Mifel')
ClabeAccount.create(abm_code: '044', short_name:'SCOTIABANK', corporate_name:'Scotiabank Inverlat, S.A.')
ClabeAccount.create(abm_code: '058', short_name:'BANREGIO', corporate_name:'Banco Regional de Monterrey, S.A., Institución de Banca Múltiple, Banregio Grupo Financiero')
ClabeAccount.create(abm_code: '059', short_name:'INVEX', corporate_name:'Banco Invex, S.A., Institución de Banca Múltiple, Invex Grupo Financiero')
ClabeAccount.create(abm_code: '060', short_name:'BANSI', corporate_name:'Bansi, S.A., Institución de Banca Múltiple')
ClabeAccount.create(abm_code: '062', short_name:'AFIRME', corporate_name:'Banca Afirme, S.A., Institución de Banca Múltiple')
ClabeAccount.create(abm_code: '072', short_name:'BANORTE', corporate_name:'Banco Mercantil del Norte, S.A., Institución de Banca Múltiple, Grupo Financiero Banorte')
ClabeAccount.create(abm_code: '102', short_name:'THE ROYAL BANK', corporate_name:'The Royal Bank of Scotland México, S.A., Institución de Banca Múltiple')
ClabeAccount.create(abm_code: '103', short_name:'AMERICAN EXPRESS', corporate_name:'American Express Bank (México), S.A., Institución de Banca Múltiple')
ClabeAccount.create(abm_code: '106', short_name:'BAMSA', corporate_name:'Bank of America México, S.A., Institución de Banca Múltiple, Grupo Financiero Bank of America')
ClabeAccount.create(abm_code: '108', short_name:'TOKYO', corporate_name:'Bank of Tokyo-Mitsubishi UFJ (México), S.A.')
ClabeAccount.create(abm_code: '110', short_name:'JP MORGAN', corporate_name:'Banco J.P. Morgan, S.A., Institución de Banca Múltiple, J.P. Morgan Grupo Financiero')
ClabeAccount.create(abm_code: '112', short_name:'BMONEX', corporate_name:'Banco Monex, S.A., Institución de Banca Múltiple')
ClabeAccount.create(abm_code: '113', short_name:'VE POR MAS', corporate_name:'Banco Ve Por Mas, S.A. Institución de Banca Múltiple')
ClabeAccount.create(abm_code: '116', short_name:'ING', corporate_name:'ING Bank (México), S.A., Institución de Banca Múltiple, ING Grupo Financiero')
ClabeAccount.create(abm_code: '124', short_name:'DEUTSCHE BANK', corporate_name:'Deutsche Bank México, S.A., Institución de Banca Múltiple')
ClabeAccount.create(abm_code: '126', short_name:'CREDIT SUISSE', corporate_name:'Banco Credit Suisse (México), S.A. Institución de Banca Múltiple, Grupo Financiero Credit Suisse (México)')
ClabeAccount.create(abm_code: '127', short_name:'AZTECA', corporate_name:'Banco Azteca, S.A. Institución de Banca Múltiple.')
ClabeAccount.create(abm_code: '128', short_name:'AUTOFIN', corporate_name:'Banco Autofin México, S.A. Institución de Banca Múltiple')
ClabeAccount.create(abm_code: '129', short_name:'BARCLAYS', corporate_name:'Barclays Bank México, S.A., Institución de Banca Múltiple, Grupo Financiero Barclays México')
ClabeAccount.create(abm_code: '130', short_name:'COMPARTAMOS', corporate_name:'Banco Compartamos, S.A., Institución de Banca Múltiple')
ClabeAccount.create(abm_code: '131', short_name:'BANCO FAMSA', corporate_name:'Banco Ahorro Famsa, S.A., Institución de Banca Múltiple')
ClabeAccount.create(abm_code: '132', short_name:'BMULTIVA', corporate_name:'Banco Multiva, S.A., Institución de Banca Múltiple, Multivalores Grupo Financiero')
ClabeAccount.create(abm_code: '133', short_name:'ACTINVER', corporate_name:'Banco Actinver, S.A. Institución de Banca Múltiple, Grupo Financiero Actinver')
ClabeAccount.create(abm_code: '134', short_name:'WAL-MART', corporate_name:'Banco Wal-Mart de México Adelante, S.A., Institución de Banca Múltiple')
ClabeAccount.create(abm_code: '135', short_name:'NAFIN', corporate_name:'Nacional Financiera, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo')
ClabeAccount.create(abm_code: '136', short_name:'INTERBANCO', corporate_name:'Inter Banco, S.A. Institución de Banca Múltiple')
ClabeAccount.create(abm_code: '137', short_name:'BANCOPPEL', corporate_name:'BanCoppel, S.A., Institución de Banca Múltiple')
ClabeAccount.create(abm_code: '138', short_name:'ABC CAPITAL', corporate_name:'ABC Capital, S.A., Institución de Banca Múltiple')
ClabeAccount.create(abm_code: '139', short_name:'UBS BANK', corporate_name:'UBS Bank México, S.A., Institución de Banca Múltiple, UBS Grupo Financiero')
ClabeAccount.create(abm_code: '140', short_name:'CONSUBANCO', corporate_name:'Consubanco, S.A. Institución de Banca Múltiple')
ClabeAccount.create(abm_code: '141', short_name:'VOLKSWAGEN', corporate_name:'Volkswagen Bank, S.A., Institución de Banca Múltiple')
ClabeAccount.create(abm_code: '143', short_name:'CIBANCO', corporate_name:'CIBanco, S.A.')
ClabeAccount.create(abm_code: '145', short_name:'BBASE', corporate_name:'Banco Base, S.A., Institución de Banca Múltiple')
ClabeAccount.create(abm_code: '156', short_name:'SABADELL', corporate_name:'Banco de Sabadell, S.A.')
ClabeAccount.create(abm_code: '166', short_name:'BANSEFI', corporate_name:'Banco del Ahorro Nacional y Servicios Financieros, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo')
ClabeAccount.create(abm_code: '168', short_name:'HIPOTECARIA FEDERAL', corporate_name:'Sociedad Hipotecaria Federal, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo')
ClabeAccount.create(abm_code: '600', short_name:'MONEXCB', corporate_name:'Monex Casa de Bolsa, S.A. de C.V. Monex Grupo Financiero')
ClabeAccount.create(abm_code: '601', short_name:'GBM', corporate_name:'GBM Grupo Bursátil Mexicano, S.A. de C.V. Casa de Bolsa')
ClabeAccount.create(abm_code: '602', short_name:'MASARI', corporate_name:'Masari Casa de Bolsa, S.A.')
ClabeAccount.create(abm_code: '605', short_name:'VALUE', corporate_name:'Value, S.A. de C.V. Casa de Bolsa')
ClabeAccount.create(abm_code: '606', short_name:'ESTRUCTURADORES', corporate_name:'Estructuradores del Mercado de Valores Casa de Bolsa, S.A. de C.V.')
ClabeAccount.create(abm_code: '607', short_name:'TIBER', corporate_name:'Casa de Cambio Tiber, S.A. de C.V.')
ClabeAccount.create(abm_code: '608', short_name:'VECTOR', corporate_name:'Vector Casa de Bolsa, S.A. de C.V.')
ClabeAccount.create(abm_code: '610', short_name:'B&B', corporate_name:'B y B, Casa de Cambio, S.A. de C.V.')
ClabeAccount.create(abm_code: '614', short_name:'ACCIVAL', corporate_name:'Acciones y Valores Banamex, S.A. de C.V., Casa de Bolsa')
ClabeAccount.create(abm_code: '615', short_name:'MERRILL LYNCH', corporate_name:'Merrill Lynch México, S.A. de C.V. Casa de Bolsa')
ClabeAccount.create(abm_code: '616', short_name:'FINAMEX', corporate_name:'Casa de Bolsa Finamex, S.A. de C.V.')
ClabeAccount.create(abm_code: '617', short_name:'VALMEX', corporate_name:'Valores Mexicanos Casa de Bolsa, S.A. de C.V.')
ClabeAccount.create(abm_code: '618', short_name:'UNICA', corporate_name:'Unica Casa de Cambio, S.A. de C.V.')
ClabeAccount.create(abm_code: '619', short_name:'MAPFRE', corporate_name:'MAPFRE Tepeyac, S.A.')
ClabeAccount.create(abm_code: '620', short_name:'PROFUTURO', corporate_name:'Profuturo G.N.P., S.A. de C.V., Afore')
ClabeAccount.create(abm_code: '621', short_name:'CB ACTINVER', corporate_name:'Actinver Casa de Bolsa, S.A. de C.V.')
ClabeAccount.create(abm_code: '622', short_name:'OACTIN', corporate_name:'OPERADORA ACTINVER, S.A. DE C.V.')
ClabeAccount.create(abm_code: '623', short_name:'SKANDIA', corporate_name:'Skandia Vida, S.A. de C.V.')
ClabeAccount.create(abm_code: '626', short_name:'CBDEUTSCHE', corporate_name:'Deutsche Securities, S.A. de C.V. CASA DE BOLSA')
ClabeAccount.create(abm_code: '627', short_name:'ZURICH', corporate_name:'Zurich Compañía de Seguros, S.A.')
ClabeAccount.create(abm_code: '628', short_name:'ZURICHVI', corporate_name:'Zurich Vida, Compañía de Seguros, S.A.')
ClabeAccount.create(abm_code: '629', short_name:'SU CASITA', corporate_name:'Hipotecaria Su Casita, S.A. de C.V. SOFOM ENR')
ClabeAccount.create(abm_code: '630', short_name:'CB INTERCAM', corporate_name:'Intercam Casa de Bolsa, S.A. de C.V.')
ClabeAccount.create(abm_code: '631', short_name:'CI BOLSA', corporate_name:'CI Casa de Bolsa, S.A. de C.V.')
ClabeAccount.create(abm_code: '632', short_name:'BULLTICK CB', corporate_name:'Bulltick Casa de Bolsa, S.A., de C.V.')
ClabeAccount.create(abm_code: '633', short_name:'STERLING', corporate_name:'Sterling Casa de Cambio, S.A. de C.V.')
ClabeAccount.create(abm_code: '634', short_name:'FINCOMUN', corporate_name:'Fincomún, Servicios Financieros Comunitarios, S.A. de C.V.')
ClabeAccount.create(abm_code: '636', short_name:'HDI SEGUROS', corporate_name:'HDI Seguros, S.A. de C.V.')
ClabeAccount.create(abm_code: '637', short_name:'ORDER', corporate_name:'Order Express Casa de Cambio, S.A. de C.V.')
ClabeAccount.create(abm_code: '638', short_name:'AKALA', corporate_name:'Akala, S.A. de C.V., Sociedad Financiera Popular')
ClabeAccount.create(abm_code: '640', short_name:'CB JPMORGAN', corporate_name:'J.P. Morgan Casa de Bolsa, S.A. de C.V. J.P. Morgan Grupo Financiero')
ClabeAccount.create(abm_code: '642', short_name:'REFORMA', corporate_name:'Operadora de Recursos Reforma, S.A. de C.V., S.F.P.')
ClabeAccount.create(abm_code: '646', short_name:'STP', corporate_name:'Sistema de Transferencias y Pagos STP, S.A. de C.V.SOFOM ENR')
ClabeAccount.create(abm_code: '647', short_name:'TELECOMM', corporate_name:'Telecomunicaciones de México')
ClabeAccount.create(abm_code: '648', short_name:'EVERCORE', corporate_name:'Evercore Casa de Bolsa, S.A. de C.V.')
ClabeAccount.create(abm_code: '649', short_name:'SKANDIA', corporate_name:'Skandia Operadora de Fondos, S.A. de C.V.')
ClabeAccount.create(abm_code: '651', short_name:'SEGMTY', corporate_name:'Seguros Monterrey New York Life, S.A de C.V.')
ClabeAccount.create(abm_code: '652', short_name:'ASEA', corporate_name:'Solución Asea, S.A. de C.V., Sociedad Financiera Popular')
ClabeAccount.create(abm_code: '653', short_name:'KUSPIT', corporate_name:'Kuspit Casa de Bolsa, S.A. de C.V.')
ClabeAccount.create(abm_code: '655', short_name:'SOFIEXPRESS', corporate_name:'J.P. SOFIEXPRESS, S.A. de C.V., S.F.P.')
ClabeAccount.create(abm_code: '656', short_name:'UNAGRA', corporate_name:'UNAGRA, S.A. de C.V., S.F.P.')
ClabeAccount.create(abm_code: '659', short_name:'OPCIONES EMPRESARIALES DEL NOROESTE', corporate_name:'OPCIONES EMPRESARIALES DEL NORESTE, S.A. DE C.V., S.F.P.')
ClabeAccount.create(abm_code: '670', short_name:'LIBERTAD', corporate_name:'Libertad Servicios Financieros, S.A. De C.V.')
ClabeAccount.create(abm_code: '901', short_name:'CLS', corporate_name:'Cls Bank International')
ClabeAccount.create(abm_code: '902', short_name:'INDEVAL', corporate_name:'SD. Indeval, S.A. de C.V.')
ClabeAccount.create(abm_code: '999', short_name:'N/A', corporate_name:'N/A')
